# Generated by Django 4.2 on 2023-04-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basisModel", "0002_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Base",),
    ]
