# Generated by Django 4.2 on 2023-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basisModel", "0003_delete_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "base",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={"db_table": "base", "managed": True,},
        ),
        migrations.DeleteModel(name="AuthGroup",),
        migrations.DeleteModel(name="AuthGroupPermissions",),
        migrations.DeleteModel(name="AuthPermission",),
        migrations.DeleteModel(name="AuthUser",),
        migrations.DeleteModel(name="AuthUserGroups",),
        migrations.DeleteModel(name="AuthUserUserPermissions",),
        migrations.DeleteModel(name="DjangoAdminLog",),
        migrations.DeleteModel(name="DjangoContentType",),
        migrations.DeleteModel(name="DjangoMigrations",),
        migrations.DeleteModel(name="DjangoSession",),
        migrations.AlterModelOptions(name="build", options={"managed": True},),
        migrations.AlterModelOptions(name="buy", options={"managed": True},),
        migrations.AlterModelOptions(name="car", options={"managed": True},),
        migrations.AlterModelOptions(name="customer", options={"managed": True},),
        migrations.AlterModelOptions(name="industry", options={"managed": True},),
        migrations.AlterModelOptions(name="sizes", options={"managed": True},),
    ]
